# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-19 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catastrophe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_title', models.CharField(max_length=200)),
                ('cat_location', models.CharField(max_length=100)),
                ('cat_pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
