# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-13 08:50
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dcp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(max_length=15000)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('userID', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)])),
                ('bumpCounter', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='post_dangers',
            name='bumps',
        ),
        migrations.RemoveField(
            model_name='post_dangers',
            name='catastrophe',
        ),
        migrations.RemoveField(
            model_name='post_dangers',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='post_dangers',
            name='reports',
        ),
        migrations.RemoveField(
            model_name='post_dangers',
            name='user',
        ),
        migrations.RemoveField(
            model_name='post_news',
            name='bumps',
        ),
        migrations.RemoveField(
            model_name='post_news',
            name='catastrophe',
        ),
        migrations.RemoveField(
            model_name='post_news',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='post_news',
            name='reports',
        ),
        migrations.RemoveField(
            model_name='post_news',
            name='user',
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 13, 8, 50, 38, 51794, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.DeleteModel(
            name='Post_Dangers',
        ),
        migrations.DeleteModel(
            name='Post_News',
        ),
    ]
