# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 14:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dcp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('1', 'Groceries'), ('2,', 'Infrastructure'), ('3', 'Tools'), ('4', 'Drugs')], max_length=1)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('location_x', models.FloatField()),
                ('location_y', models.FloatField()),
                ('image', models.ImageField(upload_to='')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('bump_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('report_cnt', models.PositiveSmallIntegerField(default=0)),
                ('visibility', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('1', 'Groceries'), ('2,', 'Infrastructure'), ('3', 'Tools'), ('4', 'Drugs')], max_length=1)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('radius', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('location_x', models.FloatField()),
                ('location_y', models.FloatField()),
                ('image', models.ImageField(upload_to='')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('visibility', models.BooleanField(default=True)),
            ],
        ),
    ]
