# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-24 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_map',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='show_picture',
            field=models.BooleanField(default=True),
        ),
    ]
