# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-27 16:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dcp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_Dangers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('locationString', models.CharField(default='', max_length=200, null=True)),
                ('location_x', models.FloatField(null=True)),
                ('location_y', models.FloatField(null=True)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to='upload/goods/')),
                ('visibility', models.BooleanField(default=True)),
                ('timeline_badge_color', models.CharField(default='yellow', max_length=100)),
                ('timeline_glyphicon', models.CharField(default='glyphicon-alert', max_length=100)),
                ('catastrophe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcp.Catastrophe')),
                ('comments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dcp.Comment_Relation')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post_News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('locationString', models.CharField(default='', max_length=200, null=True)),
                ('location_x', models.FloatField(null=True)),
                ('location_y', models.FloatField(null=True)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to='upload/goods/')),
                ('visibility', models.BooleanField(default=True)),
                ('timeline_badge_color', models.CharField(default='yellow', max_length=100)),
                ('timeline_glyphicon', models.CharField(default='glyphicon-bullhorn', max_length=100)),
                ('catastrophe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcp.Catastrophe')),
                ('comments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dcp.Comment_Relation')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post_Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('locationString', models.CharField(default='', max_length=200, null=True)),
                ('location_x', models.FloatField(null=True)),
                ('location_y', models.FloatField(null=True)),
                ('created_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to='upload/goods/')),
                ('visibility', models.BooleanField(default=True)),
                ('timeline_badge_color', models.CharField(default='yellow', max_length=100)),
                ('timeline_glyphicon', models.CharField(default='glyphicon-question-sign', max_length=100)),
                ('catastrophe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcp.Catastrophe')),
                ('comments', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dcp.Comment_Relation')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
