# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-20 18:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Goverment',
            new_name='Government',
        ),
        migrations.RenameModel(
            old_name='Invite_Goverment',
            new_name='Invite_Government',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='goverment',
            new_name='government',
        ),
    ]
