# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 14:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dcp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorysGoods',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('glyphiconString', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='offer_immaterial',
            name='bumps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dcp.Bump_Relation'),
        ),
        migrations.AlterField(
            model_name='offer_immaterial',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dcp.Comment_Relation'),
        ),
        migrations.AlterField(
            model_name='offer_immaterial',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='offer_immaterial',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='offer_immaterial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/goods/'),
        ),
        migrations.AlterField(
            model_name='offer_immaterial',
            name='reports',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dcp.Report_Relation'),
        ),
        migrations.AlterField(
            model_name='offer_immaterial',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='offer_material',
            name='bumps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dcp.Bump_Relation'),
        ),
        migrations.AlterField(
            model_name='offer_material',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dcp.CategorysGoods'),
        ),
        migrations.AlterField(
            model_name='offer_material',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dcp.Comment_Relation'),
        ),
        migrations.AlterField(
            model_name='offer_material',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='offer_material',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='offer_material',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/goods/'),
        ),
        migrations.AlterField(
            model_name='offer_material',
            name='reports',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dcp.Report_Relation'),
        ),
        migrations.AlterField(
            model_name='offer_material',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='search_immaterial',
            name='bumps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dcp.Bump_Relation'),
        ),
        migrations.AlterField(
            model_name='search_immaterial',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dcp.Comment_Relation'),
        ),
        migrations.AlterField(
            model_name='search_immaterial',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='search_immaterial',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search_immaterial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/goods/'),
        ),
        migrations.AlterField(
            model_name='search_immaterial',
            name='radius',
            field=models.PositiveSmallIntegerField(choices=[(0, '0 km'), (1, '1 km'), (2, '2 km'), (5, '5 km'), (10, '10 km'), (50, '50 km'), (100, '100 km'), (1000, '1000 km')], default=0),
        ),
        migrations.AlterField(
            model_name='search_immaterial',
            name='reports',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dcp.Report_Relation'),
        ),
        migrations.AlterField(
            model_name='search_immaterial',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='search_material',
            name='bumps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dcp.Bump_Relation'),
        ),
        migrations.AlterField(
            model_name='search_material',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dcp.CategorysGoods'),
        ),
        migrations.AlterField(
            model_name='search_material',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dcp.Comment_Relation'),
        ),
        migrations.AlterField(
            model_name='search_material',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='search_material',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search_material',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/goods/'),
        ),
        migrations.AlterField(
            model_name='search_material',
            name='radius',
            field=models.PositiveSmallIntegerField(choices=[(0, '0 km'), (1, '1 km'), (2, '2 km'), (5, '5 km'), (10, '10 km'), (50, '50 km'), (100, '100 km'), (1000, '1000 km')], default=0),
        ),
        migrations.AlterField(
            model_name='search_material',
            name='reports',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dcp.Report_Relation'),
        ),
        migrations.AlterField(
            model_name='search_material',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
