# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='government',
            name='catastrophes',
        ),
        migrations.RemoveField(
            model_name='ngo',
            name='catastrophes',
        ),
        migrations.AddField(
            model_name='catastrophe',
            name='government',
            field=models.ManyToManyField(related_name='catastrophes', to='dcp.Government'),
        ),
        migrations.AddField(
            model_name='catastrophe',
            name='ngos',
            field=models.ManyToManyField(related_name='catastrophes', to='dcp.Ngo'),
        ),
    ]
