# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 20:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dcp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missedpeople',
            name='catastrophe',
        ),
        migrations.AlterField(
            model_name='missedpeople',
            name='characteristics',
            field=models.CharField(default=datetime.datetime(2016, 6, 12, 20, 54, 22, 853881, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='missedpeople',
            name='description',
            field=models.CharField(default='(keine Beschreibung)', max_length=5000),
            preserve_default=False,
        ),
    ]
