# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcp', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='begin_date',
            field=models.DateTimeField(null=True),
        ),
    ]
