# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcp', '0002_auto_20160629_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catastrophe',
            old_name='government',
            new_name='governments',
        ),
    ]
