# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-25 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcp', '0002_auto_20160625_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='locationString',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='immaterial_goods',
            name='locationString',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='offer_material',
            name='locationString',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='search_material',
            name='locationString',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
