# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-13 08:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dcp', '0002_auto_20160713_1050'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post_Questions',
            new_name='Post_Question',
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 13, 8, 55, 0, 139388, tzinfo=utc), verbose_name='date published'),
        ),
    ]
