# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-25 16:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcp', '0003_auto_20160625_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catastrophe',
            old_name='Location',
            new_name='locationString',
        ),
        migrations.RenameField(
            model_name='catastrophe',
            old_name='PubDate',
            new_name='pubDate',
        ),
        migrations.RenameField(
            model_name='catastrophe',
            old_name='Title',
            new_name='title',
        ),
        migrations.AlterUniqueTogether(
            name='catastrophe',
            unique_together=set([('title', 'locationString')]),
        ),
    ]
