# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 17:38
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dcp', '0003_auto_20160525_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer_Immaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_cnt', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Search_Immaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('location_x', models.FloatField()),
                ('location_y', models.FloatField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('visibility', models.BooleanField(default=True)),
                ('radius', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('catastrophe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dcp.Catastrophe')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Search_Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('location_x', models.FloatField()),
                ('location_y', models.FloatField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('visibility', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('1', 'Groceries'), ('2,', 'Infrastructure'), ('3', 'Tools'), ('4', 'Drugs')], max_length=1)),
                ('image', models.ImageField(upload_to='')),
                ('radius', models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('catastrophe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dcp.Catastrophe')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='offer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='search',
            name='user',
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
        migrations.DeleteModel(
            name='Search',
        ),
    ]
