# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-25 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcp', '0004_auto_20160625_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catastrophe',
            old_name='pubDate',
            new_name='date_created',
        ),
    ]
