# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 06:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcp', '0004_auto_20160627_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_dangers',
            name='bumps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dcp.Bump_Relation'),
        ),
        migrations.AddField(
            model_name='post_dangers',
            name='reports',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dcp.Report_Relation'),
        ),
        migrations.AddField(
            model_name='post_news',
            name='bumps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dcp.Bump_Relation'),
        ),
        migrations.AddField(
            model_name='post_news',
            name='reports',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dcp.Report_Relation'),
        ),
        migrations.AddField(
            model_name='post_questions',
            name='bumps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dcp.Bump_Relation'),
        ),
        migrations.AddField(
            model_name='post_questions',
            name='reports',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dcp.Report_Relation'),
        ),
    ]
