# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 17:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dcp', '0004_auto_20160525_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer_Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(max_length=500, null=True)),
                ('location_x', models.FloatField(null=True)),
                ('location_y', models.FloatField(null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('visibility', models.BooleanField(default=True)),
                ('category', models.CharField(choices=[('1', 'Groceries'), ('2,', 'Infrastructure'), ('3', 'Tools'), ('4', 'Drugs')], max_length=1)),
                ('image', models.ImageField(upload_to='')),
                ('bump_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('report_cnt', models.PositiveSmallIntegerField(default=0)),
                ('catastrophe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dcp.Catastrophe')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='offer_immaterial',
            name='bump_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='offer_immaterial',
            name='catastrophe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dcp.Catastrophe'),
        ),
        migrations.AddField(
            model_name='offer_immaterial',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='offer_immaterial',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='offer_immaterial',
            name='location_x',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='offer_immaterial',
            name='location_y',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='offer_immaterial',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='offer_immaterial',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offer_immaterial',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='search_immaterial',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search_immaterial',
            name='location_x',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='search_immaterial',
            name='location_y',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='search_immaterial',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='search_material',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search_material',
            name='location_x',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='search_material',
            name='location_y',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='search_material',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
