# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcp', '0005_auto_20160623_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cars',
            field=models.ManyToManyField(blank=True, to='dcp.Car'),
        ),
        migrations.AlterField(
            model_name='event',
            name='specials',
            field=models.ManyToManyField(blank=True, to='dcp.Special'),
        ),
    ]
