# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-26 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dcp', '0005_auto_20160525_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer_Immaterial_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.TextField(max_length=500, null=True)),
                ('key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dcp.Offer_Immaterial')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Offer_Material_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.TextField(max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Search_Immaterial_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.TextField(max_length=500, null=True)),
                ('key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dcp.Search_Immaterial')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Search_Material_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.TextField(max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='offer_material',
            name='image',
            field=models.ImageField(upload_to='/upload/...'),
        ),
        migrations.AlterField(
            model_name='search_material',
            name='image',
            field=models.ImageField(upload_to='/upload/...'),
        ),
        migrations.AddField(
            model_name='search_material_comment',
            name='key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dcp.Search_Material'),
        ),
        migrations.AddField(
            model_name='offer_material_comment',
            name='key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dcp.Offer_Material'),
        ),
    ]
