# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-26 00:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcp', '0006_auto_20160625_2246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='governmentinvite',
            old_name='government',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='ngoinvite',
            old_name='ngo',
            new_name='organization',
        ),
        migrations.AlterUniqueTogether(
            name='governmentinvite',
            unique_together=set([('profile', 'organization')]),
        ),
        migrations.AlterUniqueTogether(
            name='ngoinvite',
            unique_together=set([('profile', 'organization')]),
        ),
    ]
