# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcp', '0006_auto_20160628_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
