# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcp', '0007_question_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='catastrophe',
        ),
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
    ]
