# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dcp', '0007_auto_20160529_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.TextField(max_length=5000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment_Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='offer_immaterial_comment',
            name='key',
        ),
        migrations.RemoveField(
            model_name='offer_material_comment',
            name='key',
        ),
        migrations.RemoveField(
            model_name='search_immaterial_comment',
            name='key',
        ),
        migrations.RemoveField(
            model_name='search_material_comment',
            name='key',
        ),
        migrations.DeleteModel(
            name='Offer_Immaterial_Comment',
        ),
        migrations.DeleteModel(
            name='Offer_Material_Comment',
        ),
        migrations.DeleteModel(
            name='Search_Immaterial_Comment',
        ),
        migrations.DeleteModel(
            name='Search_Material_Comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcp.Comment_Relation'),
        ),
        migrations.AddField(
            model_name='offer_immaterial',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dcp.Comment_Relation'),
        ),
        migrations.AddField(
            model_name='offer_material',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dcp.Comment_Relation'),
        ),
        migrations.AddField(
            model_name='search_immaterial',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dcp.Comment_Relation'),
        ),
        migrations.AddField(
            model_name='search_material',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dcp.Comment_Relation'),
        ),
    ]
