# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 18:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcp', '0008_auto_20160529_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer_immaterial',
            name='catastrophe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcp.Catastrophe'),
        ),
        migrations.AlterField(
            model_name='offer_immaterial',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='offer_immaterial',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='offer_material',
            name='catastrophe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcp.Catastrophe'),
        ),
        migrations.AlterField(
            model_name='offer_material',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='offer_material',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='search_immaterial',
            name='catastrophe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcp.Catastrophe'),
        ),
        migrations.AlterField(
            model_name='search_immaterial',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='search_immaterial',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='search_material',
            name='catastrophe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcp.Catastrophe'),
        ),
        migrations.AlterField(
            model_name='search_material',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='search_material',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
