# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 20:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dcp', '0009_auto_20160529_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer_Immaterial_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.TextField(max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Offer_Material_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.TextField(max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Search_Immaterial_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.TextField(max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Search_Material_Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.TextField(max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_relation',
        ),
        migrations.RemoveField(
            model_name='offer_immaterial',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='offer_immaterial',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='offer_immaterial',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='offer_material',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='offer_material',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='offer_material',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='search_immaterial',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='search_immaterial',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='search_immaterial',
            name='lon',
        ),
        migrations.RemoveField(
            model_name='search_material',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='search_material',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='search_material',
            name='lon',
        ),
        migrations.AlterField(
            model_name='offer_immaterial',
            name='catastrophe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dcp.Catastrophe'),
        ),
        migrations.AlterField(
            model_name='offer_immaterial',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='offer_immaterial',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='offer_material',
            name='catastrophe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dcp.Catastrophe'),
        ),
        migrations.AlterField(
            model_name='offer_material',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='offer_material',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='search_immaterial',
            name='catastrophe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dcp.Catastrophe'),
        ),
        migrations.AlterField(
            model_name='search_immaterial',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='search_immaterial',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='search_material',
            name='catastrophe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dcp.Catastrophe'),
        ),
        migrations.AlterField(
            model_name='search_material',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='search_material',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Comment_Relation',
        ),
        migrations.AddField(
            model_name='search_material_comment',
            name='key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dcp.Search_Material'),
        ),
        migrations.AddField(
            model_name='search_immaterial_comment',
            name='key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dcp.Search_Immaterial'),
        ),
        migrations.AddField(
            model_name='offer_material_comment',
            name='key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dcp.Offer_Material'),
        ),
        migrations.AddField(
            model_name='offer_immaterial_comment',
            name='key',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dcp.Offer_Immaterial'),
        ),
    ]
