# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcp', '0009_remove_choice_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='choice_text',
        ),
        migrations.AddField(
            model_name='question',
            name='choice_text',
            field=models.CharField(default=2, max_length=200),
        ),
    ]
