# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 21:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcp', '0009_auto_20160529_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer_immaterial',
            name='location_x',
        ),
        migrations.RemoveField(
            model_name='offer_immaterial',
            name='location_y',
        ),
        migrations.RemoveField(
            model_name='offer_material',
            name='location_x',
        ),
        migrations.RemoveField(
            model_name='offer_material',
            name='location_y',
        ),
        migrations.RemoveField(
            model_name='search_immaterial',
            name='location_x',
        ),
        migrations.RemoveField(
            model_name='search_immaterial',
            name='location_y',
        ),
        migrations.RemoveField(
            model_name='search_material',
            name='location_x',
        ),
        migrations.RemoveField(
            model_name='search_material',
            name='location_y',
        ),
    ]
