# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-29 23:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcp', '0010_auto_20160629_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='choice_text',
        ),
        migrations.AddField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dcp.Question'),
        ),
    ]
