# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 23:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dcp', '0010_auto_20160531_2230'),
        ('dcp', '0010_auto_20160530_2304'),
    ]

    operations = [
    ]
