# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 09:05
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dcp', '0012_auto_20160601_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('text', models.TextField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment_Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='offer_immaterial_comment',
            name='key',
        ),
        migrations.RemoveField(
            model_name='offer_material_comment',
            name='key',
        ),
        migrations.RemoveField(
            model_name='search_immaterial_comment',
            name='key',
        ),
        migrations.RemoveField(
            model_name='search_material_comment',
            name='key',
        ),
        migrations.AlterField(
            model_name='offer_immaterial',
            name='catastrophe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcp.Catastrophe'),
        ),
        migrations.AlterField(
            model_name='offer_immaterial',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='offer_immaterial',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='offer_immaterial',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='offer_material',
            name='catastrophe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcp.Catastrophe'),
        ),
        migrations.AlterField(
            model_name='offer_material',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='offer_material',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='offer_material',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='search_immaterial',
            name='catastrophe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcp.Catastrophe'),
        ),
        migrations.AlterField(
            model_name='search_immaterial',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='search_immaterial',
            name='radius',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='search_immaterial',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='search_immaterial',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='search_material',
            name='catastrophe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcp.Catastrophe'),
        ),
        migrations.AlterField(
            model_name='search_material',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='search_material',
            name='radius',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='search_material',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='search_material',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Offer_Immaterial_Comment',
        ),
        migrations.DeleteModel(
            name='Offer_Material_Comment',
        ),
        migrations.DeleteModel(
            name='Search_Immaterial_Comment',
        ),
        migrations.DeleteModel(
            name='Search_Material_Comment',
        ),
        migrations.AddField(
            model_name='comment',
            name='realtion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcp.Comment_Relation'),
        ),
        migrations.AddField(
            model_name='offer_immaterial',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dcp.Comment_Relation'),
        ),
        migrations.AddField(
            model_name='offer_material',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dcp.Comment_Relation'),
        ),
        migrations.AddField(
            model_name='search_immaterial',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dcp.Comment_Relation'),
        ),
        migrations.AddField(
            model_name='search_material',
            name='comments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dcp.Comment_Relation'),
        ),
    ]
