# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-02 14:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dcp', '0013_auto_20160702_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 2, 14, 10, 4, 870761, tzinfo=utc), verbose_name='date published'),
        ),
    ]
