# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 11:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dcp', '0013_auto_20160601_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='realtion',
            new_name='relation',
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
