# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcp', '0014_auto_20160601_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(default='Bla', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer_immaterial',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='offer_material',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search_immaterial',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='search_material',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
