# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-09 09:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dcp', '0014_auto_20160702_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='user',
        ),
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.CharField(default='Ja; Nein', max_length=500),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 9, 9, 48, 35, 858525, tzinfo=utc), verbose_name='date published'),
        ),
    ]
