# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 20:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dcp', '0015_auto_20160602_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Bump_Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Report_Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='comment_relation',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='offer_immaterial',
            name='bump_date',
        ),
        migrations.RemoveField(
            model_name='offer_immaterial',
            name='report_cnt',
        ),
        migrations.RemoveField(
            model_name='offer_material',
            name='bump_date',
        ),
        migrations.RemoveField(
            model_name='offer_material',
            name='report_cnt',
        ),
        migrations.AddField(
            model_name='report',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcp.Report_Relation'),
        ),
        migrations.AddField(
            model_name='report',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bump',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcp.Bump_Relation'),
        ),
        migrations.AddField(
            model_name='bump',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offer_immaterial',
            name='bumps',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dcp.Bump_Relation'),
        ),
        migrations.AddField(
            model_name='offer_immaterial',
            name='reports',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dcp.Report_Relation'),
        ),
        migrations.AddField(
            model_name='offer_material',
            name='bumps',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dcp.Bump_Relation'),
        ),
        migrations.AddField(
            model_name='offer_material',
            name='reports',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dcp.Report_Relation'),
        ),
        migrations.AddField(
            model_name='search_immaterial',
            name='bumps',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dcp.Bump_Relation'),
        ),
        migrations.AddField(
            model_name='search_immaterial',
            name='reports',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dcp.Report_Relation'),
        ),
        migrations.AddField(
            model_name='search_material',
            name='bumps',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dcp.Bump_Relation'),
        ),
        migrations.AddField(
            model_name='search_material',
            name='reports',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dcp.Report_Relation'),
        ),
    ]
