# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcp', '0016_auto_20160602_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer_material',
            name='category',
            field=models.CharField(choices=[('1', 'Lebensmittel'), ('2', 'Infrastruktur'), ('3', 'Werkzeug'), ('4', 'Medizin'), ('5', 'Sonstiges')], max_length=1),
        ),
        migrations.AlterField(
            model_name='search_material',
            name='category',
            field=models.CharField(choices=[('1', 'Lebensmittel'), ('2', 'Infrastruktur'), ('3', 'Werkzeug'), ('4', 'Medizin'), ('5', 'Sonstiges')], max_length=1),
        ),
    ]
