# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-09 09:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dcp', '0016_auto_20160709_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='choices',
            new_name='choice_text',
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 9, 9, 56, 2, 396229, tzinfo=utc), verbose_name='date published'),
        ),
    ]
