# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcp', '0017_auto_20160603_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer_immaterial',
            name='timeline_badge_color',
            field=models.CharField(default='red', max_length=100),
        ),
        migrations.AddField(
            model_name='offer_immaterial',
            name='timeline_glyphicon',
            field=models.CharField(default='glyphicon-transfer', max_length=100),
        ),
        migrations.AddField(
            model_name='offer_material',
            name='timeline_badge_color',
            field=models.CharField(default='red', max_length=100),
        ),
        migrations.AddField(
            model_name='offer_material',
            name='timeline_glyphicon',
            field=models.CharField(default='glyphicon-transfer', max_length=100),
        ),
        migrations.AddField(
            model_name='search_immaterial',
            name='timeline_badge_color',
            field=models.CharField(default='blue', max_length=100),
        ),
        migrations.AddField(
            model_name='search_immaterial',
            name='timeline_glyphicon',
            field=models.CharField(default='glyphicon-search', max_length=100),
        ),
        migrations.AddField(
            model_name='search_material',
            name='timeline_badge_color',
            field=models.CharField(default='blue', max_length=100),
        ),
        migrations.AddField(
            model_name='search_material',
            name='timeline_glyphicon',
            field=models.CharField(default='glyphicon-search', max_length=100),
        ),
    ]
