# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-09 11:11
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dcp', '0017_auto_20160709_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='voted_users',
            field=models.ManyToManyField(null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 9, 11, 11, 12, 25330, tzinfo=utc), verbose_name='date published'),
        ),
    ]
